import app.routes.customers.listCustomers
import app.routes.customers.insertCustomers
import app.routes.customers.findCustomer
import app.routes.customers.deleteCustomers
import app.routes.accounts.listAccounts
import app.routes.accounts.newAccounts
import app.routes.accounts.findAccount
import app.routes.accounts.deleteAccount
import app.routes.movements.listMovements
import app.routes.movements.newMovements